eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
  instance:
    health-check-url-path: /actuator/health
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
logging:
  file: C:/Log/${spring.application.name}.log
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 6001
spring:
  application:
    name: admin-server
  boot:
    admin:
      notify:
        mail:
          enabled: true
          from: 17674757619@163.com
          to: 1174578722@qq.com
  mail:
    host: smtp.163.com
    #password: lhmenlxvqvyjbage
    password: ACGODNVXJUXBTDII
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 17674757619@163.com
#    port: 587

  security:
    user:
      name: admin
      password: admin
