server:
  port: 9003

spring:
  application:
    name: service-client1
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:7001/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
