server:
  port: 9005

spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:7001/
  application:
    name: service-client2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
