server:
  port: 9005

spring:
  application:
    name: service-client2
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:7001/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
