server:
  port: 7001
spring:
  application:
    name: service-config1
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/TZhaoJie/mySpringCloud/
          searchPaths: properties
          username: ""
          password: ""

