server:
  port: 10002

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

spring:
  application:
    name: eurka-server
